format = '''$time$all'''

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[cmd_duration]
disabled = false

[directory]
format = 'in [$path]($style)[$read_only]($read_only_style) '

[time]
disabled = false
format = '[$time]($style) '
